### PR TITLE
Fix small typo and link in docs

### PR DESCRIPTION
**Pull request by missy-davies**
👋🏻 Hello, I was going through the docs and noticed a broken link and small typo. 

I'm working on using LangSmith with [GitLab on the Code Creation team](https://gitlab.com/missy-gitlab) :)

### CODE REVIEW

**Comment by missy-davies** [comment]
👋🏻 @agola11 Maybe you're right right person to tag here?

**Comment by hinthornw** [comment]
Good catch!

**Comment by missy-davies** [comment]
@hinthornw Looks like the merge was blocked by an authorization to deploy - are you able to unblock that?

**Comment by agola11** [comment]
Thanks @missy-davies !

**Review by agola11 — APPROVED** [review]

**Pull request merged**
